title: Ascension Energy Technologies
description: Educational blog on ascension energy technologies, quantum phenomena including the Casimir Effect, zero-point energy, Tesla Coils, Rodin Coils, and consciousness studies with a minimal store for crystals and tools
url: "https://lifeplus1.github.io"
baseurl: "/AET"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima - Disabled to use custom layouts and CSS
future: true  # Allow future-dated posts for testing

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  store:
    output: true
    permalink: /store/:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "_store"
    values:
      layout: product

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
